# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-31 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170731_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_number',
            field=models.IntegerField(),
        ),
    ]
