# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lecture_lecture_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
