# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='ta',
            new_name='tas',
        ),
    ]
