# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-23 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170906_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='absolute_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
