# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-16 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image_root_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='page_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
