# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-03 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20171002_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=255)),
                ('path', models.CharField(default='', max_length=255)),
                ('url', models.CharField(default='', max_length=255)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='path',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='size',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='type',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='publication',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication'),
        ),
    ]
