# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='nickname',
        ),
    ]
