# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170728_0307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='memberType',
        ),
        migrations.AddField(
            model_name='profile',
            name='pictureUrl',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='researchArea',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='selfIntro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='studentType',
            field=models.CharField(choices=[('1', 'College'), ('2', 'Master'), ('3', 'PHD')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
