# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-13 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170813_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pictureUrl',
            field=models.URLField(),
        ),
    ]
