# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170817_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studentType',
            field=models.CharField(choices=[('1', 'College'), ('2', 'Master'), ('3', 'PHD'), ('4', 'Teacher'), ('5', 'Alumni')], max_length=1),
        ),
    ]
