# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180126_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
