# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pictureUrl',
            field=models.URLField(default='http://elsa.cs.nthu.edu.tw:8000/static/users_avaters/default.jpg'),
        ),
    ]
