# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-11 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
