# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-01 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180320_0230'),
        ('user', '0009_profile_nick_name'),
    ]

    operations = [
    ]
